// <auto-generated />
using Loan_Buddy_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loan_Buddy_Api.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220508165004_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Loan_Buddy_Api.Data.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 155,
                            Email = "Carl@gmail.com",
                            Name = "Carl"
                        },
                        new
                        {
                            UserId = 156,
                            Email = "Karen@gmail.com",
                            Name = "Karen"
                        },
                        new
                        {
                            UserId = 157,
                            Email = "Joe@gmail.com",
                            Name = "Joe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
