// <auto-generated />
namespace Loan_Buddy_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class loanAgreementFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loanAgreementFK));
        
        string IMigrationMetadata.Id
        {
            get { return "202208162109444_loanAgreementFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
