// <auto-generated />
namespace Loan_Buddy_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class transaction5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transaction5));
        
        string IMigrationMetadata.Id
        {
            get { return "202208152030594_transaction5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
